# Generated by Django 5.1.6 on 2025-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('nutricionista', 'Nutricionista')], max_length=15)),
            ],
        ),
    ]
